kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: ocs-metrics-exporter
allowPrivilegedContainer: true
allowHostNetwork: false
allowHostDirVolumePlugin: false
priority:
allowedCapabilities:
allowHostPorts: false
allowHostPID: false
allowHostIPC: false
# Set to false as we write to RootFilesystem inside metrics-exporter container
readOnlyRootFilesystem: false
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
volumes:
  - configMap
  - downwardAPI
  - emptyDir
  - hostPath
  - projected
users:
  - system:serviceaccount:openshift-storage:ocs-metrics-exporter